export default [
  {
    name: "Palo Alto",
    description: "#16a085 → #f4d03f",
    css: "linear-gradient(-60deg, #16a085 0%, #f4d03f 100%)",
    height: 400,
    img: "/resources/py-icon.png",
    text: "Python",
  },
  {
    name: "Saint Petersburg",
    description: "#f5f7fa → #c3cfe2",
    css: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)",
    height: 400,
    img: "/resources/c-icon.png",
    text: "C/C++",
  },
  {
    name: "Deep Blue",
    description: "#e0c3fc → #8ec5fc",
    css: "linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)",
    height: 400,
    img: "/resources/react-icon.png",
    text: "ReactJS",
  },
  {
    name: "Fruit BLend",
    description: "#f9d423 → #ff4e50",
    css: "linear-gradient(to right, #f9d423 0%, #ff4e50 100%)",
    height: 200,
    img: "/resources/html-icon.png",
    text: "HTML5",
  },
  {
    name: "Perfect White",
    description: "#fdfbfb → #ebedee",
    css: "linear-gradient(135deg, #E3FDF5 0%, #FFE6FA 100%)",
    height: 400,
    img: "/resources/java-icon.png",
    text: "Java",
  },
  {
    name: "Strong Stick",
    description: "#a8caba → #5d4157",
    css: "linear-gradient(to right, #a8caba 0%, #5d4157 100%)",
    height: 400,
    img: "/resources/git-icon.png",
    text: "Git/Github",
  },
  {
    name: "Lemon Gate",
    description: "#96fbc4 → #f9f586",
    css: "linear-gradient(135deg, #96fbc4 0%, #f9f586 100%)",
    height: 400,
    img: "/resources/js-icon.png",
    text: "JavaScript",
  },
  {
    name: "Happy Fisher",
    description: "#89f7fe → #66a6ff",
    css: "linear-gradient(120deg, #89f7fe 0%, #66a6ff 100%)",
    height: 400,
    img: "/resources/css-icon.png",
    text: "CSS3",
  },
  {
    name: "Sunny Morning",
    description: "#f6d365 → #fda085",
    css: "linear-gradient(135deg, #f6d365 0%, #fda085 100%)",
    height: 200,
    img: "/resources/swift-icon.png",
    text: "Swift",
  },
];
